### ISSUE TITLE
FRC Predictor Back-End: Single match simulation

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/FRC2607_DiscordBot#4]
Basically just take the various scoring elements, call into other people's code that give you how many points a team should score in a given match / how much defense they should play, and compute a final match score.

**Comment by JohnathonNow** [comment]
https://github.com/JohnathonNow/FRC2607_DiscordBot/blob/c80d1bbb3650ae807881d6b04a225876818f64cb/handlers/FRC/MatchPredictor.java#L17

**Comment by CrunchyCuber** [comment]
I'll claim this one

**Comment by JohnathonNow** [comment]
`public int getGoals(int team)` and have it just return a random number for now.

**Comment by JohnathonNow** [comment]
Resolved in #17
