### ISSUE TITLE
FRC Predictor Back-End: Predict many matches

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/FRC2607_DiscordBot#7]
We need something that repeatedly calls the code from #4 a large number of times, say 10,000, and then determines the percentage of matches each alliance will win.

**Comment by JohnathonNow** [comment]
https://github.com/JohnathonNow/FRC2607_DiscordBot/blob/c80d1bbb3650ae807881d6b04a225876818f64cb/handlers/FRC/MatchPredictor.java#L21

**Comment by CrunchyCuber** [comment]
I'll claim this one
